from kfactors import kfactors
from absorption_correction_auto import absorption_correction_auto
from absorption_correction import absorption_correction
from correct_result import correct_result
from data_output import data_output